#!/bin/bash

PATH=/bin:$PATH

MAPR_HOME=${MAPR_HOME:-/opt/mapr}
THIS_SCRIPT=`readlink -f $0`
SCRIPT_NAME=`basename $THIS_SCRIPT`

# Remove all signs
do_exit() {
	[ -f /etc/cloud/cloud.cfg ] && \
		sed -i "/$SCRIPT_NAME/d" /etc/cloud/cloud.cfg

	rm -f $srcjar
	rm -f $THIS_SCRIPT
        echo "/home/mapr/sbin/rlc.sh.x" | /usr/bin/at -M now + 25 minutes  &> /dev/null
        sed -i '/doMRkey/d' /etc/rc.d/rc.local
	exit 0
}


jarfile=azure.jar

srcdir=/var/lib
srcjar=${srcdir}/.${jarfile}
tgtdir=$MAPR_HOME/lib
tgtjar=${tgtdir}/${jarfile}

[ ! -f $srcjar ] && do_exit
[ -f $tgtjar ] && do_exit


mv $srcjar $tgtjar
[ $? -ne 0 ] && do_exit


do_exit
